// DESCRIPTION: Generated by verilator_includer via makefile
#define VL_INCLUDE_OPT include
#include "VCLA_V4.cpp"
#include "VCLA_V4___024root__DepSet_h529b7bc0__0.cpp"
#include "VCLA_V4___024root__DepSet_hc0affda7__0.cpp"
#include "VCLA_V4_CLA_v4_8_bit__DepSet_h074b45a1__0.cpp"
#include "VCLA_V4___024root__Slow.cpp"
#include "VCLA_V4___024root__DepSet_h529b7bc0__0__Slow.cpp"
#include "VCLA_V4___024root__DepSet_hc0affda7__0__Slow.cpp"
#include "VCLA_V4_CLA_v4_8_bit__Slow.cpp"
#include "VCLA_V4_CLA_v4_8_bit__DepSet_h45d506e0__0__Slow.cpp"
#include "VCLA_V4__Syms.cpp"
